-- AlterTable
ALTER TABLE "User"
    ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS "locationUpdatedAt" TIMESTAMP(3);
